services:
    _defaults:
        autowire: true
        autoconfigure: true

    Morfeditorial\MachinimaTelegramAdapter\:
        resource: '../src/'
        exclude: '../src/MachinimaTelegramAdapterBundle.php'

    Morfeditorial\MachinimaTelegramAdapter\Oidc\TelegramOidcConfiguration:
        arguments:
            $clientId: '%env(default:0:int:TELEGRAM_OIDC_CLIENT_ID)%'
            $clientSecret: '%env(default:0:TELEGRAM_OIDC_CLIENT_SECRET)%'
            $redirectUri: '%env(default:0:TELEGRAM_OIDC_REDIRECT_URI)%'
            $label: 'Telegram'

    Morfeditorial\MachinimaTelegramAdapter\Oidc\TelegramOidcProvider:
        tags: ['app.identity_provider']
